# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html> <title>IoTMeter</title> <meta charset=UTF-8  /> <meta name=viewport  content=\"max-width=767px, initial-scale=1\" /> <script type=\"application/javascript\" src=\"main/static/loadLibrary.js\"></script> <body id=mainBody  style=\"background-color: black;\" onload=\"loadLibrary()\">"""
