# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html>
<!-- The Modal -->
<div class=\"modal fade\" id=\"myModal\">
    <div class=\"modal-dialog modal-lg\">
        <div class=\"modal-content\">

            <!-- Modal Header -->
            <div class=\"modal-header\">
                <h4 class=\"modal-title\">Proccess status</h4>
                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>
            </div>

            <div class=\"modal-body\">
                <div id=\"val\"></div>
                <div class=\"font-weight-bold\" id=\"stat\"></div>
            </div>
            <div class=\"modal-footer\">
                <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>
            </div>

        </div>
    </div>
</div>

<div class=\"container-sm text-white\">
    <div class=\"container-fluid mt-3 mb-2 text-center bg border border-secondary\"><span class=\"dim\">Wattmeter setup</span></div>
    <div class=\"container text-center\" id=\"settingTable\">
        <div class=\"row\">
            <div class=\"col\">
                <h6 class=\"unit\">Info</h6>
            </div>
            <div class=\"col\">
                <h6 class=\"unit\">State</h6>
            </div>
        </div>
    </div>
    <div class=\"container-sm mt-3 text-center\" id=\"evseSetting\"></div>
    <div class=\"container-fluid mt-3 text-center bg border border-secondary\"><span class=\"dim\">Wi-Fi Client Setup</span></div>
    <div class=\"container-fluid text-white text-center\">
        <table class=\"table table-borderless text-center text-white\">
            <tbody>
                <tr class=\"ssidTable\">
                    <td id=\"ssid\" colspan=\"2\"></td>
                    <td></td>
                </tr>
                <tr>
                    <td class=\"w-50 unit\">Pass</td>
                    <td class=\"w-50\"><input id=\"passwordField\" name=\"password\" type=\"password\" size=\"15\" /></td>
                </tr>
            </tbody>
        </table>
        <div class=\"container text-center text-white\">
            <div class=\"row mt-3\">
                <div class=\"col\">
                    <h6 id=\"wifiStatus\"></h6>
                </div>
            </div>
            <div class=\"btn-group\"><button id=\"setSSID\" type=\"button\" class=\"btn btn-primary\">submit</button><button id=\"refreshSSID\" type=\"button\" class=\"btn btn-primary\">refresh</button></div>
        </div>
        <br />
    </div>
    <footer></footer>
</div>

</html>"""
